let themes = {
	"a11y-dark":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/a11y-dark.min.css",
	"a11y-light":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/a11y-light.min.css",
	agate:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/agate.min.css",
	"an-old-hope":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/an-old-hope.min.css",
	androidstudio:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/androidstudio.min.css",
	"arduino-light":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/arduino-light.min.css",
	arta: "https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/arta.min.css",
	ascetic:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/ascetic.min.css",
	"atom-one-dark-reasonable":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/atom-one-dark-reasonable.min.css",
	"atom-one-dark":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/atom-one-dark.min.css",
	"atom-one-light":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/atom-one-light.min.css",
	"brown-paper":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/brown-paper.min.css",
	"codepen-embed":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/codepen-embed.min.css",
	"color-brewer":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/color-brewer.min.css",
	dark: "https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/dark.min.css",
	default:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/default.min.css",
	devibeans:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/devibeans.min.css",
	docco:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/docco.min.css",
	far: "https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/far.min.css",
	felipec:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/felipec.min.css",
	foundation:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/foundation.min.css",
	"github-dark-dimmed":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/github-dark-dimmed.min.css",
	"github-dark":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/github-dark.min.css",
	github:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/github.min.css",
	gml: "https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/gml.min.css",
	googlecode:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/googlecode.min.css",
	"gradient-dark":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/gradient-dark.min.css",
	"gradient-light":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/gradient-light.min.css",
	grayscale:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/grayscale.min.css",
	hybrid:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/hybrid.min.css",
	idea: "https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/idea.min.css",
	"intellij-light":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/intellij-light.min.css",
	"ir-black":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/ir-black.min.css",
	"isbl-editor-dark":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/isbl-editor-dark.min.css",
	"isbl-editor-light":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/isbl-editor-light.min.css",
	"kimbie-dark":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/kimbie-dark.min.css",
	"kimbie-light":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/kimbie-light.min.css",
	lightfair:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/lightfair.min.css",
	lioshi:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/lioshi.min.css",
	magula:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/magula.min.css",
	"mono-blue":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/mono-blue.min.css",
	"monokai-sublime":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/monokai-sublime.min.css",
	monokai:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/monokai.min.css",
	"night-owl":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/night-owl.min.css",
	"nnfx-dark":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/nnfx-dark.min.css",
	"nnfx-light":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/nnfx-light.min.css",
	nord: "https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/nord.min.css",
	obsidian:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/obsidian.min.css",
	"panda-syntax-dark":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/panda-syntax-dark.min.css",
	"panda-syntax-light":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/panda-syntax-light.min.css",
	"paraiso-dark":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/paraiso-dark.min.css",
	"paraiso-light":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/paraiso-light.min.css",
	pojoaque:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/pojoaque.min.css",
	purebasic:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/purebasic.min.css",
	"qtcreator-dark":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/qtcreator-dark.min.css",
	"qtcreator-light":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/qtcreator-light.min.css",
	rainbow:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/rainbow.min.css",
	routeros:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/routeros.min.css",
	"school-book":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/school-book.min.css",
	"shades-of-purple":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/shades-of-purple.min.css",
	srcery:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/srcery.min.css",
	"stackoverflow-dark":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/stackoverflow-dark.min.css",
	"stackoverflow-light":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/stackoverflow-light.min.css",
	sunburst:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/sunburst.min.css",
	"tokyo-night-dark":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/tokyo-night-dark.min.css",
	"tokyo-night-light":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/tokyo-night-light.min.css",
	"tomorrow-night-blue":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/tomorrow-night-blue.min.css",
	"tomorrow-night-bright":
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/tomorrow-night-bright.min.css",
	vs: "https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/vs.min.css",
	vs2015:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/vs2015.min.css",
	xcode:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/xcode.min.css",
	xt256:
		"https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/xt256.min.css",
};
